# hotel-api application.yml
server:
  port: 9595  servlet:    session:      cookie:        http-only: true
spring:  application:
    name: hotel-api
  datasource:    platform: h2
eureka:  client:    service-url:
      defaultZone: http://localhost:8761/eureka